name: Publish
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
on:
  push:
    branches: [master]
  workflow_run: 
    workflows: ["Test and Benchmark"]
    branches: [master]
    types: 
      - completed
jobs:
  publish:
    needs: [test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.41.5]
    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Publish jsr
        run: deno publish
