name: Publish
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.41.2]
    steps:
      - name: Install packages
        run: apt-get install -y hyperfine
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Publish jsr
        run: deno publish
