name: Test Deno Module

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.39.1, 1.38.1]
    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Publish jsr
        run: deno publish
