name: Publish
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
on:
  workflow_run: 
    workflows: ["Test and Benchmark"]
    branches: [master]
    types: 
      - completed
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
      - name: Publish jsr
        run: deno publish
