name: Test and Benchmark
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
on:
  push:
    branches: [master]
  pull_request:
    branches: []
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.39.1, 1.38.1, 1.41.3]
    steps:
      - name: Install hyperfine
        run: sudo apt-get install -y hyperfine
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Unit Testing
        id: test
        run: deno task ok
      - name: Benchmark
        id: benchmark
        run: |
        {
          bench=$(deno task bench)
          echo "::set-output name=benchmarks::$bench"
        }
      - name: Auto Comment
        uses: mshick/add-pr-comment@v2
        with:
        message: `${{ steps.benchmark.outputs.benchmarks }}`
