name: Test and Benchmark
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
on:
  push:
    branches: [master, feat/**, ref/**, release-*]
  pull_request:
    branches: []
jobs:
  test:
    strategy:
      matrix:
        deno-version: [1.39.1, 1.38.1, 1.41.3, 1.45.5, 1.46.3, 2.0.0, 2.1.10]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install hyperfine
        run: sudo apt-get install -y hyperfine
        if: runner.os == 'Linux' && always()
      - name: Install hyperfine
        run: brew install hyperfine
        if: runner.os == 'macOS' && always()
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Unit Testing
        id: test
        run: deno task ok
      - name: Benchmark
        id: benchmark
        run: deno task bench
        if: runner.os == 'Linux' || runner.os == 'macOS' && always()
  test-canary:
    strategy:
      matrix:
        deno-version: [2.0.0]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - name: Install hyperfine
        run: sudo apt-get install -y hyperfine
        if: runner.os == 'Linux' && always()
      - name: Install hyperfine
        run: brew install hyperfine
        if: runner.os == 'macOS' && always()
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Unit Testing
        id: test
        run: deno task ok
      - name: Benchmark
        id: benchmark
        run: deno task bench
        if: runner.os == 'Linux' || runner.os == 'macOS' && always()
